spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transactFlow
    username: postgres
    password: "yourpassword"
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
  application:
    name: transaction-processing


  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: payment-group
    topics:
      raw-payments-topic: raw-payments-topic